#!/bin/bash

current_full_path="$(cd "$(dirname "$0")"; pwd -P)/$(basename "$0")"

echo -e "\n"
echo -e "\033[1mAnalysing files using PHPStan...\033[0m"
echo ""

vendor/bin/phpstan analyse -c .github/linters/phpstan.neon
if [[ $? -ne 0 ]]; then
    echo "PHPStan analysis failed. Commit aborted."
    echo -e "\n"

    # show current file path
    echo -e "\033[1mPre-commit checks were executed by ${current_full_path}.\033[0m"
    echo -e "\n"

    exit 1
fi

# show current file path
echo -e "\033[1mPre-commit checks were executed by ${current_full_path}.\033[0m"
echo -e "\n"

# If all checks pass, allow the commit
exit 0
