name: Dependabot auto-merge & tests
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    uses: centralnicgroup-opensource/rtldev-middleware-shareable-workflows/.github/workflows/php-sdk-test.yml@RSRMID-2092-doc-php-sdk-features-and-comparision
    secrets: inherit